# Pandas in Python

In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\alokverma\anaconda3\lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\alokverma\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\alokverma\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\alokverma\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\alokverma\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [3]:
pd.__version__

'3.0.1'

In [4]:
# Series

In [5]:
l = [11,32,45,12]

In [6]:
s = pd.Series(l)

In [7]:
print(s)
print(type(s))

0    11
1    32
2    45
3    12
dtype: int64
<class 'pandas.Series'>

In [8]:
a = pd.Series(l,index=["A","B","C","D"])

In [9]:
a

A    11
B    32
C    45
D    12
dtype: int64

In [14]:
Data = {"Ab":100,"aB":200,"cd":400}

In [15]:
print(Data)
print(type(Data))

{'Ab': 100, 'aB': 200, 'cd': 400}
<class 'dict'>

In [16]:
d = pd.Series(Data)

In [17]:
d

Ab    100
aB    200
cd    400
dtype: int64

In [18]:
# DataFrame

In [29]:
d = {
    "Name":["Amit","Sumit","Raju"],
    "Age":[23,25,26],
    "Marks":[90,98,89]
}

In [30]:
print(d)
print(type(d))

{'Name': ['Amit', 'Sumit', 'Raju'], 'Age': [23, 25, 26], 'Marks': [90, 98, 89]}
<class 'dict'>

In [31]:
d

{'Name': ['Amit', 'Sumit', 'Raju'], 'Age': [23, 25, 26], 'Marks': [90, 98, 89]}

In [32]:
df = pd.DataFrame(d)

In [33]:
df

    Name  Age  Marks
0   Amit   23     90
1  Sumit   25     98
2   Raju   26     89

In [35]:
df

    Name  Age  Marks
0   Amit   23     90
1  Sumit   25     98
2   Raju   26     89

In [36]:
df.head(1)

   Name  Age  Marks
0  Amit   23     90

In [37]:
df.head(100)

    Name  Age  Marks
0   Amit   23     90
1  Sumit   25     98
2   Raju   26     89

In [40]:
df.tail()

    Name  Age  Marks
0   Amit   23     90
1  Sumit   25     98
2   Raju   26     89

In [44]:
df[["Name","Age"]]

    Name  Age
0   Amit   23
1  Sumit   25
2   Raju   26

In [45]:
df.head(2:3)

SyntaxError: invalid syntax (3393118808.py, line 1)

In [49]:
df[["Name","Marks"]][1:3]

    Name  Marks
1  Sumit     98
2   Raju     89

In [50]:
# loc vs iloc

In [51]:
# df.lo["row","column"]

In [55]:
df.loc[1:3,["Name","Age"]]

    Name  Age
1  Sumit   25
2   Raju   26

In [56]:
df.iloc[1:3,1:3]

   Age  Marks
1   25     98
2   26     89

In [58]:
df.iloc[1:3,[-1]]

   Marks
1     98
2     89

In [62]:
d = {
    "A" :[1,2,3,4,5,None,7],
    "B":["Amit","Sumit","Raju","nitin","Rakesh","mukesh","Vijay"],
    "C":[98,65,77,35,76,None,73]
}

In [63]:
df = pd.DataFrame(d)

In [64]:
df

     A       B     C
0  1.0    Amit  98.0
1  2.0   Sumit  65.0
2  3.0    Raju  77.0
3  4.0   nitin  35.0
4  5.0  Rakesh  76.0
5  NaN  mukesh   NaN
6  7.0   Vijay  73.0

In [65]:
df.shape

(7, 3)

In [66]:
df.describe()

              A          C
count  6.000000   6.000000
mean   3.666667  70.666667
std    2.160247  20.617145
min    1.000000  35.000000
25%    2.250000  67.000000
50%    3.500000  74.500000
75%    4.750000  76.750000
max    7.000000  98.000000

In [67]:
df.isnull()

       A      B      C
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False
5   True  False   True
6  False  False  False

In [69]:
df.isnull()

       A      B      C
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False
5   True  False   True
6  False  False  False

In [68]:
df.isnull().sum()

A    1
B    0
C    1
dtype: int64

In [70]:
df.drop(columns="A")

        B     C
0    Amit  98.0
1   Sumit  65.0
2    Raju  77.0
3   nitin  35.0
4  Rakesh  76.0
5  mukesh   NaN
6   Vijay  73.0

In [71]:
df

     A       B     C
0  1.0    Amit  98.0
1  2.0   Sumit  65.0
2  3.0    Raju  77.0
3  4.0   nitin  35.0
4  5.0  Rakesh  76.0
5  NaN  mukesh   NaN
6  7.0   Vijay  73.0

In [72]:
df.drop(columns="A",inplace=True)

In [73]:
df

        B     C
0    Amit  98.0
1   Sumit  65.0
2    Raju  77.0
3   nitin  35.0
4  Rakesh  76.0
5  mukesh   NaN
6   Vijay  73.0

In [74]:
df.dropna()

        B     C
0    Amit  98.0
1   Sumit  65.0
2    Raju  77.0
3   nitin  35.0
4  Rakesh  76.0
6   Vijay  73.0

In [75]:
df

        B     C
0    Amit  98.0
1   Sumit  65.0
2    Raju  77.0
3   nitin  35.0
4  Rakesh  76.0
5  mukesh   NaN
6   Vijay  73.0

In [76]:
df.dropna(inplace=True)

In [77]:
df

        B     C
0    Amit  98.0
1   Sumit  65.0
2    Raju  77.0
3   nitin  35.0
4  Rakesh  76.0
6   Vijay  73.0

In [84]:
d = {
    "A":["1","2","3","4","5"],
    "B":[23,32,44,23,None],
    "C":["Amit","Sumit","Raju","vinit","mukesh"]
}

In [85]:
df = pd.DataFrame(d)

In [86]:
df

   A     B       C
0  1  23.0    Amit
1  2  32.0   Sumit
2  3  44.0    Raju
3  4  23.0   vinit
4  5   NaN  mukesh

In [87]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      str
 1   B       4 non-null      float64
 2   C       5 non-null      str
dtypes: float64(1), str(2)
memory usage: 281.0 bytes

In [88]:
df["A"] = pd.to_numeric(df["A"],errors="coerce")

In [89]:
df

   A     B       C
0  1  23.0    Amit
1  2  32.0   Sumit
2  3  44.0    Raju
3  4  23.0   vinit
4  5   NaN  mukesh

In [90]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       4 non-null      float64
 2   C       5 non-null      str
dtypes: float64(1), int64(1), str(1)
memory usage: 276.0 bytes

In [91]:
df

   A     B       C
0  1  23.0    Amit
1  2  32.0   Sumit
2  3  44.0    Raju
3  4  23.0   vinit
4  5   NaN  mukesh

In [92]:
df.fillna(1000)

   A       B       C
0  1    23.0    Amit
1  2    32.0   Sumit
2  3    44.0    Raju
3  4    23.0   vinit
4  5  1000.0  mukesh

In [93]:
df

   A     B       C
0  1  23.0    Amit
1  2  32.0   Sumit
2  3  44.0    Raju
3  4  23.0   vinit
4  5   NaN  mukesh

In [96]:
df["B"]= df["B"].fillna(df["B"].mean())

In [97]:
df

   A     B       C
0  1  23.0    Amit
1  2  32.0   Sumit
2  3  44.0    Raju
3  4  23.0   vinit
4  5  30.5  mukesh

In [ ]:
# Create a DataFrame and find only missing value 
# create a Dataset for pandas and apply write down the concept of loc vs iloc 
# crrate a dataset and drop only null values from the Dataset
# create dataset for pandas and Add a column in Dataset

In [32]:
d = {
    "A":["1","2","3","4","5"],
    "B":[23,32,44,23,None],
    "C":["Amit","Sumit","Raju","vinit","mukesh"]
}

In [33]:
import pandas as pd

In [34]:
df_1 = pd.DataFrame(d)

In [35]:
df_1

   A     B       C
0  1  23.0    Amit
1  2  32.0   Sumit
2  3  44.0    Raju
3  4  23.0   vinit
4  5   NaN  mukesh

In [36]:
df_1.isnull().sum()

A    0
B    1
C    0
dtype: int64

In [37]:
# loc vs iloc in pandas

In [38]:
# loc - it is help to slicing the data into Dataframe.
# it is location based or access through the name of the column.

df_1.loc[2:6,"A"]

2    3
3    4
4    5
Name: A, dtype: str

In [39]:
# iloc = it is stand for the index based location acessing in pandas Dataframe

In [40]:
df_1.iloc[:,1]

0    23.0
1    32.0
2    44.0
3    23.0
4     NaN
Name: B, dtype: float64

In [41]:
# drop null values

In [42]:
df_1.dropna()

   A     B      C
0  1  23.0   Amit
1  2  32.0  Sumit
2  3  44.0   Raju
3  4  23.0  vinit

In [43]:
df_1

   A     B       C
0  1  23.0    Amit
1  2  32.0   Sumit
2  3  44.0    Raju
3  4  23.0   vinit
4  5   NaN  mukesh

In [44]:
df_1["B"].mean()

np.float64(30.5)

In [45]:
df_1["B"].median()

27.5

In [46]:
# fill

In [47]:
df_1["B"].fillna(100)

0     23.0
1     32.0
2     44.0
3     23.0
4    100.0
Name: B, dtype: float64

In [48]:
df_1

   A     B       C
0  1  23.0    Amit
1  2  32.0   Sumit
2  3  44.0    Raju
3  4  23.0   vinit
4  5   NaN  mukesh

In [49]:
df_1["B"] = df_1["B"].fillna(df_1["B"].mean())

In [50]:
df_1

   A     B       C
0  1  23.0    Amit
1  2  32.0   Sumit
2  3  44.0    Raju
3  4  23.0   vinit
4  5  30.5  mukesh

In [51]:
df_1

   A     B       C
0  1  23.0    Amit
1  2  32.0   Sumit
2  3  44.0    Raju
3  4  23.0   vinit
4  5  30.5  mukesh

In [52]:
df = pd.DataFrame(d,index="id","Marks","Name")

SyntaxError: positional argument follows keyword argument (3152815761.py, line 1)

In [54]:
d = {
    "id":["1","2","3","4","5"],
    "Marks":[23,32,44,23,None],
    "Name":["Amit","Sumit","Raju","vinit","mukesh"]
}

In [55]:
df = pd.DataFrame(d)

In [57]:
df.head(2)

  id  Marks   Name
0  1   23.0   Amit
1  2   32.0  Sumit

In [58]:
df.tail(2)

  id  Marks    Name
3  4   23.0   vinit
4  5    NaN  mukesh

In [59]:
df.describe()

           Marks
count   4.000000
mean   30.500000
std     9.949874
min    23.000000
25%    23.000000
50%    27.500000
75%    35.000000
max    44.000000

In [60]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      5 non-null      str
 1   Marks   4 non-null      float64
 2   Name    5 non-null      str
dtypes: float64(1), str(2)
memory usage: 281.0 bytes

In [62]:
df["id"] = pd.to_numeric(df['id'],errors = "coerce")

In [63]:
df

   id  Marks    Name
0   1   23.0    Amit
1   2   32.0   Sumit
2   3   44.0    Raju
3   4   23.0   vinit
4   5    NaN  mukesh

In [64]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      5 non-null      int64
 1   Marks   4 non-null      float64
 2   Name    5 non-null      str
dtypes: float64(1), int64(1), str(1)
memory usage: 276.0 bytes

In [66]:
df["city"] = ["lko","noida","lko","bbk","Delhi"]

In [67]:
df

   id  Marks    Name   city
0   1   23.0    Amit    lko
1   2   32.0   Sumit  noida
2   3   44.0    Raju    lko
3   4   23.0   vinit    bbk
4   5    NaN  mukesh  Delhi

In [68]:
df["abc"] = "aaaa"

In [69]:
df

   id  Marks    Name   city   abc
0   1   23.0    Amit    lko  aaaa
1   2   32.0   Sumit  noida  aaaa
2   3   44.0    Raju    lko  aaaa
3   4   23.0   vinit    bbk  aaaa
4   5    NaN  mukesh  Delhi  aaaa

In [70]:
# dropna()
# drop() - remove columns

In [72]:
df.drop(columns="abc",inplace=True)

In [73]:
df

   id  Marks    Name   city
0   1   23.0    Amit    lko
1   2   32.0   Sumit  noida
2   3   44.0    Raju    lko
3   4   23.0   vinit    bbk
4   5    NaN  mukesh  Delhi

In [74]:
df.dropna(inplace=True)

In [75]:
df

   id  Marks   Name   city
0   1   23.0   Amit    lko
1   2   32.0  Sumit  noida
2   3   44.0   Raju    lko
3   4   23.0  vinit    bbk

In [76]:
df['Marks'].sum()

np.float64(122.0)

In [77]:
df['Marks'].count()

np.int64(4)

In [78]:
df['Marks'].min()

23.0

In [79]:
df['Marks'].max()

44.0

In [80]:
df

   id  Marks   Name   city
0   1   23.0   Amit    lko
1   2   32.0  Sumit  noida
2   3   44.0   Raju    lko
3   4   23.0  vinit    bbk

In [82]:
df['Marks'].sort_values()

0    23.0
3    23.0
1    32.0
2    44.0
Name: Marks, dtype: float64

In [83]:
df

   id  Marks   Name   city
0   1   23.0   Amit    lko
1   2   32.0  Sumit  noida
2   3   44.0   Raju    lko
3   4   23.0  vinit    bbk

In [85]:
df['id'].groupby(df["city"]).count()

city
bbk      1
lko      2
noida    1
Name: id, dtype: int64

In [89]:
data_1 = {
    "id":[1,2,3,4,9,11],
    "Name":["Amit","Sumit","Raju","vinit","ankit","Rahul"] 
}

In [93]:
data_2 = {
    "id":[1,2,3,5,6,7,18,19],
    "Marks":[34,67,33,57,89,65,88,56]
}

In [94]:
df_1 = pd.DataFrame(data_1)

In [95]:
df_2 = pd.DataFrame(data_2)

In [96]:
df_1

   id   Name
0   1   Amit
1   2  Sumit
2   3   Raju
3   4  vinit
4   9  ankit
5  11  Rahul

In [97]:
df_2

   id  Marks
0   1     34
1   2     67
2   3     33
3   5     57
4   6     89
5   7     65
6  18     88
7  19     56

In [98]:
# merge

In [102]:
df_3 = pd.merge(df_1,df_2,how="inner",on="id")

df_3

   id   Name  Marks
0   1   Amit     34
1   2  Sumit     67
2   3   Raju     33

In [103]:
df_4 = pd.merge(df_1,df_2,how="left",on="id")

df_4

   id   Name  Marks
0   1   Amit   34.0
1   2  Sumit   67.0
2   3   Raju   33.0
3   4  vinit    NaN
4   9  ankit    NaN
5  11  Rahul    NaN

In [104]:
df_5 = pd.merge(df_1,df_2,how="right",on="id")

df_5

   id   Name  Marks
0   1   Amit     34
1   2  Sumit     67
2   3   Raju     33
3   5    NaN     57
4   6    NaN     89
5   7    NaN     65
6  18    NaN     88
7  19    NaN     56

In [105]:
df_6 = pd.merge(df_1,df_2,how="outer",on="id")

df_6

    id   Name  Marks
0    1   Amit   34.0
1    2  Sumit   67.0
2    3   Raju   33.0
3    4  vinit    NaN
4    5    NaN   57.0
5    6    NaN   89.0
6    7    NaN   65.0
7    9  ankit    NaN
8   11  Rahul    NaN
9   18    NaN   88.0
10  19    NaN   56.0

In [106]:
df_6.nunique()

id       11
Name      6
Marks     8
dtype: int64

In [117]:
df_1

   id   Name
0   1   Amit
1   2  Sumit
2   3   Raju
3   4  vinit
4   9  ankit
5  11  Rahul

In [115]:
df_2

   id  Marks
0   1     34
1   2     67
2   3     33
3   5     57
4   6     89
5   7     65
6  18     88
7  19     56

In [121]:
df_3["Marks"][1]==33

np.False_

In [122]:
df_3

   id   Name  Marks
0   1   Amit     34
1   2  Sumit     67
2   3   Raju     33

In [139]:
Data_1 = {
    "ID":[1,2,3,4,6],
    "Name":["Amit","Samad","Raju","Vivek","Kunal"],
    "Age":[23,21,22,20,22]
}

dff = pd.DataFrame(Data_1)

In [140]:
dff

   ID   Name  Age
0   1   Amit   23
1   2  Samad   21
2   3   Raju   22
3   4  Vivek   20
4   6  Kunal   22

In [141]:
dff['Age'].duplicated()

0    False
1    False
2    False
3    False
4     True
Name: Age, dtype: bool

In [142]:
dff['Age'].duplicated().sum()

np.int64(1)

In [150]:
dff.drop_duplicates(subset="Age",inplace=True)

In [151]:
dff

   ID   Name  Age
0   1   Amit   23
1   2  Samad   21
2   3   Raju   22
3   4  Vivek   20

In [152]:
dff['Age']>21

0     True
1    False
2     True
3    False
Name: Age, dtype: bool

In [153]:
dff[['Age']]>21

     Age
0   True
1  False
2   True
3  False

In [154]:
df_3

   id   Name  Marks
0   1   Amit     34
1   2  Sumit     67
2   3   Raju     33

In [155]:
df_3.rename(columns={"Marks":"Age"})

   id   Name  Age
0   1   Amit   34
1   2  Sumit   67
2   3   Raju   33

In [156]:
df_3.to_csv("BBd.csv")